# -*- coding: utf-8 -*-
"""Carevo123fix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAH81PGdNemeD-WBN5OnkGdyhjVpHKSF
"""

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.callbacks import (
    EarlyStopping,
    TensorBoard,
    Callback,
    ModelCheckpoint
)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("dataset_clean.csv")

print(df.shape)

df.head()

columns_used = [

    "keahlian",
    "minat",
    "pendidikan",
    "sertifikasi",
    "ipk",

    "kategori_keahlian",

    "label_karir",

    "label_karir_sederhana",

    "profil_gabungan"
]

def clean_text(text):

    text = str(text).lower()

    text = re.sub(
        r"[^a-zA-Z0-9 ]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

text_columns = [

    "keahlian",
    "minat",
    "pendidikan",
    "sertifikasi",
    "kategori_keahlian",
    "profil_gabungan"
]

for col in text_columns:

    df[col] = (
        df[col]
        .fillna("unknown")
        .apply(clean_text)
    )

df["ipk"] = (
    df["ipk"]
    .fillna(0)
    .astype(str)
)

df["combined_profile"] = (

    df["keahlian"] + " " +

    df["minat"] + " " +

    df["kategori_keahlian"]
)

df["input_text"] = (

    df["combined_profile"] + " " +

    df["pendidikan"] + " " +

    df["sertifikasi"] + " " +

    df["ipk"]
)

df[[
    "input_text",
    "label_karir_sederhana"
]].head()

label_encoder = LabelEncoder()

df["label_encoded"] = (

    label_encoder.fit_transform(
        df["label_karir_sederhana"]
    )
)

num_classes = len(
    label_encoder.classes_
)

print(label_encoder.classes_)

print(
    "Jumlah kelas:",
    num_classes
)

with open(
    "label_encoder.pkl",
    "wb"
) as f:

    pickle.dump(
        label_encoder,
        f
    )

X_train, X_test, y_train, y_test = train_test_split(

    df["input_text"],

    df["label_encoded"],

    test_size=0.2,

    stratify=df["label_encoded"],

    random_state=42
)

MAX_TOKENS = 10000
MAX_LEN = 100

text_vectorizer = layers.TextVectorization(

    max_tokens=MAX_TOKENS,

    output_mode="int",

    output_sequence_length=MAX_LEN
)

text_vectorizer.adapt(
    X_train
)

BATCH_SIZE = 64

train_ds = (
    tf.data.Dataset
    .from_tensor_slices(
        (X_train, y_train)
    )
    .shuffle(5000)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

test_ds = (
    tf.data.Dataset
    .from_tensor_slices(
        (X_test, y_test)
    )
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

@tf.keras.utils.register_keras_serializable()
class AttentionLayer(
    tf.keras.layers.Layer
):

    def build(
        self,
        input_shape
    ):

        self.W = self.add_weight(

            shape=(
                input_shape[-1],
                1
            ),

            initializer="random_normal",

            trainable=True
        )

    def call(
        self,
        inputs
    ):

        score = tf.matmul(
            inputs,
            self.W
        )

        weights = tf.nn.softmax(
            score,
            axis=1
        )

        context = (
            weights *
            inputs
        )

        context = tf.reduce_sum(
            context,
            axis=1
        )

        return context

class AccuracyLogger(
    Callback
):

    def on_epoch_end(
        self,
        epoch,
        logs=None
    ):

        print(
            f"Epoch {epoch+1} | "
            f"Accuracy={logs['accuracy']:.4f}"
        )

EMBEDDING_DIM = 64

@tf.keras.utils.register_keras_serializable()
class CareerModel(
    tf.keras.Model
):

    def __init__(self):

        super().__init__()

        self.vectorizer = text_vectorizer

        self.embedding = layers.Embedding(

            MAX_TOKENS,

            EMBEDDING_DIM,

            mask_zero=True
        )

        self.bigru = layers.Bidirectional(

            layers.GRU(

                64,

                return_sequences=True,

                dropout=0.3
            )
        )

        self.attention = AttentionLayer()

        self.dense = layers.Dense(

            128,

            activation="relu"
        )

        self.dropout = layers.Dropout(
            0.5
        )

        self.output_layer = layers.Dense(

            num_classes,

            activation="softmax"
        )

    def call(
        self,
        inputs
    ):

        x = self.vectorizer(inputs)

        x = self.embedding(x)

        x = self.bigru(x)

        x = self.attention(x)

        x = self.dense(x)

        x = self.dropout(x)

        return self.output_layer(x)

model = CareerModel()

sample_batch = next(
    iter(train_ds)
)

sample_text = sample_batch[0]

_ = model(sample_text)

model.compile(

    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-3
    ),

    loss="sparse_categorical_crossentropy",

    metrics=["accuracy"]
)

model.summary()

log_dir = (
    "logs/fit/" +
    datetime.now().strftime(
        "%Y%m%d-%H%M%S"
    )
)

tensorboard = TensorBoard(

    log_dir=log_dir,

    histogram_freq=0,

    write_graph=True,

    update_freq="epoch"
)

checkpoint = ModelCheckpoint(

    "best_model.keras",

    monitor="val_accuracy",

    mode="max",

    save_best_only=True,

    verbose=1
)

early_stop = EarlyStopping(

    monitor="val_loss",

    patience=3,

    restore_best_weights=True
)

print(log_dir)

history = model.fit(

    train_ds,

    validation_data=test_ds,

    epochs=20,

    callbacks=[

        early_stop,

        checkpoint,

        tensorboard,

        AccuracyLogger()
    ]
)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir logs/fit

pred_probs = model.predict(
    X_test
)

pred_labels = np.argmax(
    pred_probs,
    axis=1
)

print(
    classification_report(
        y_test,
        pred_labels
    )
)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        pred_labels
    )
)

cm = confusion_matrix(
    y_test,
    pred_labels
)

plt.figure(
    figsize=(10,8)
)

sns.heatmap(

    cm,

    annot=True,

    fmt="d",

    xticklabels=label_encoder.classes_,

    yticklabels=label_encoder.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

model.save(
    "career_model.keras"
)

files.download(
    "career_model.keras"
)

files.download(
    "label_encoder.pkl"
)

career_jobs = {}

for category in df[
    "label_karir_sederhana"
].unique():

    jobs = (

        df[
            df[
                "label_karir_sederhana"
            ] == category
        ]

        ["label_karir"]

        .value_counts()

        .index

        .tolist()
    )

    career_jobs[
        category
    ] = jobs

print(
    "Jumlah kategori:",
    len(career_jobs)
)

def recommend_career(

    combined_profile,

    education,

    certification,

    cgpa,

    top_n=5
):

    text = (

        f"{combined_profile} "

        f"{education} "

        f"{certification} "

        f"{cgpa}"
    )

    text = clean_text(
        text
    )

    prediction = model(
        tf.constant([text]),
        training=False
    ).numpy()

    class_idx = np.argmax(
        prediction
    )

    confidence = float(
        np.max(prediction)
    )

    category = (

        label_encoder
        .inverse_transform(
            [class_idx]
        )[0]
    )

    jobs = (
        career_jobs
        .get(
            category,
            []
        )[:top_n]
    )

    return (
        category,
        confidence,
        jobs
    )

category, confidence, jobs = recommend_career(

    combined_profile="""
    python
    machine learning
    tensorflow
    sql
    data science
    """,

    education="sarjana",

    certification="""
    tensorflow developer
    aws practitioner
    """,

    cgpa=3.8,

    top_n=5
)

print(
    f"Career Domain: {category}"
)

print(
    f"Confidence: {confidence:.2%}"
)

print(
    "\nRecommended Careers:"
)

for i, job in enumerate(
    jobs,
    start=1
):

    print(
        f"{i}. {job}"
    )

category, confidence, jobs = recommend_career(

    combined_profile="""
    komunikasi administrasi arsip microsoft office
    manajemen dokumen pelayanan pelanggan
    """,

    education="sarjana",

    certification="""
    microsoft office specialist
    """,

    cgpa=3.5,

    top_n=5
)

print(category)
print(confidence)
print(jobs)

category, confidence, jobs = recommend_career(

    combined_profile="""
    digital marketing seo sem
    social media marketing content strategy
    """,

    education="sarjana",

    certification="""
    google digital marketing
    """,

    cgpa=3.4,

    top_n=5
)

print(category)
print(confidence)
print(jobs)

category, confidence, jobs = recommend_career(

    combined_profile="""
    java spring boot
    backend development api microservices
    software engineering
    """,

    education="sarjana",

    certification="""
    oracle java certification
    """,

    cgpa=3.7,

    top_n=5
)

print(category)
print(confidence)
print(jobs)

category, confidence, jobs = recommend_career(

    combined_profile="""
    teaching curriculum development
    educational assessment classroom management
    """,

    education="sarjana",

    certification="""
    sertifikat pendidik
    """,

    cgpa=3.6,

    top_n=5
)

print(category)
print(confidence)
print(jobs)

category, confidence, jobs = recommend_career(

    combined_profile="""
    ui ux design figma
    graphic design adobe illustrator
    visual communication
    """,

    education="sarjana",

    certification="""
    google ux design
    """,

    cgpa=3.5,

    top_n=5
)

print(category)
print(confidence)
print(jobs)

category, confidence, jobs = recommend_career(

    combined_profile="""
    network security ethical hacking
    penetration testing linux cyber security
    """,

    education="sarjana",

    certification="""
    comptia security+
    ceh
    """,

    cgpa=3.7,

    top_n=5
)

print(category)
print(confidence)
print(jobs)

category, confidence, jobs = recommend_career(

    combined_profile="""
    business analysis project management
    financial planning strategic management
    """,

    education="sarjana",

    certification="""
    business analyst certification
    """,

    cgpa=3.6,

    top_n=5
)

print(category)
print(confidence)
print(jobs)



