# -*- coding: utf-8 -*-
"""GenerateCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_WWDqWkX16ny9adzpPmFJyv3-6l_U4P
"""

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

from google.colab import files

def add_section_title(doc, title):

    p = doc.add_paragraph()

    run = p.add_run(title.upper())

    run.bold = True
    run.font.size = Pt(13)

    return p


def add_bullet(doc, text):

    p = doc.add_paragraph(
        style='List Bullet'
    )

    run = p.add_run(text)

    run.font.size = Pt(10)

career_group = "Data & AI"

recommended_careers = [

    "Data Scientist",

    "Machine Learning Engineer",

    "AI Engineer",

    "Data Analyst",

    "Business Intelligence Analyst"
]

def generate_ats_cv(

    # HEADER
    name,
    phone,
    email,
    linkedin,
    portfolio,
    location,

    # SUMMARY
    professional_summary,

    # EDUCATION
    education,

    # EXPERIENCE
    experiences,

    # PROJECTS
    projects,

    # CERTIFICATIONS
    certifications,

    # ACHIEVEMENTS
    achievements,

    # SKILLS
    skills,

    # LANGUAGES
    languages,

    # AI RECOMMENDATION
    career_group,
    recommended_careers,

    output_file='ATS_Professional_CV.docx'
):

    doc = Document()

    style = doc.styles['Normal']

    style.font.name = 'Times New Roman'

    style._element.rPr.rFonts.set(
        qn('w:eastAsia'),
        'Times New Roman'
    )

    style.font.size = Pt(11)

    # ==================================
    # HEADER
    # ==================================

    title = doc.add_paragraph()

    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run(
        name.upper()
    )

    run.bold = True

    run.font.size = Pt(20)

    contact = doc.add_paragraph()

    contact.alignment = WD_ALIGN_PARAGRAPH.CENTER

    contact.add_run(
        f"{phone} | {email} | {linkedin} | {portfolio}"
    )

    location_para = doc.add_paragraph()

    location_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    location_para.add_run(location)

    # ==================================
    # SUMMARY
    # ==================================

    add_section_title(
        doc,
        "Professional Summary"
    )

    doc.add_paragraph(
        professional_summary
    )

    # ==================================
    # EDUCATION
    # ==================================

    add_section_title(
        doc,
        "Education"
    )

    for edu in education:

        p = doc.add_paragraph()

        run = p.add_run(
            edu["university"]
        )

        run.bold = True

        p.add_run(
            f" | {edu['location']}"
        )

        degree = doc.add_paragraph()

        degree_run = degree.add_run(

            f"{edu['degree']} | GPA: {edu['gpa']} | {edu['year']}"
        )

        degree_run.italic = True

        for item in edu["details"]:

            add_bullet(
                doc,
                item
            )

    # ==================================
    # EXPERIENCE
    # ==================================

    add_section_title(
        doc,
        "Work Experience"
    )

    for exp in experiences:

        p = doc.add_paragraph()

        run = p.add_run(
            exp["company"]
        )

        run.bold = True

        p.add_run(
            f" | {exp['location']}"
        )

        role = doc.add_paragraph()

        role_run = role.add_run(

            f"{exp['position']} | {exp['period']}"
        )

        role_run.italic = True

        for item in exp["responsibilities"]:

            add_bullet(
                doc,
                item
            )

    # ==================================
    # PROJECTS
    # ==================================

    add_section_title(
        doc,
        "Projects"
    )

    for project in projects:

        p = doc.add_paragraph()

        run = p.add_run(
            project["title"]
        )

        run.bold = True

        doc.add_paragraph(
            project["description"]
        )

        for item in project["details"]:

            add_bullet(
                doc,
                item
            )

    # ==================================
    # CERTIFICATIONS
    # ==================================

    add_section_title(
        doc,
        "Certifications"
    )

    for cert in certifications:

        add_bullet(
            doc,
            cert
        )

    # ==================================
    # ACHIEVEMENTS
    # ==================================

    add_section_title(
        doc,
        "Achievements"
    )

    for ach in achievements:

        add_bullet(
            doc,
            ach
        )

    # ==================================
    # SKILLS
    # ==================================

    add_section_title(
        doc,
        "Skills"
    )

    doc.add_paragraph(
        skills
    )

    # ==================================
    # LANGUAGES
    # ==================================

    add_section_title(
        doc,
        "Languages"
    )

    doc.add_paragraph(
        languages
    )

    # ==================================
    # AI CAREER CATEGORY
    # ==================================

    add_section_title(
        doc,
        "AI Recommended Career Category"
    )

    doc.add_paragraph(
        career_group
    )

    # ==================================
    # AI CAREER PATH
    # ==================================

    add_section_title(
        doc,
        "AI Recommended Career Path"
    )

    for idx, career in enumerate(
        recommended_careers,
        start=1
    ):

        add_bullet(
            doc,
            f"{idx}. {career}"
        )

    doc.save(
        output_file
    )

    print(
        f"CV berhasil dibuat: {output_file}"
    )

name = "Budi Santoso"

phone = "08123456789"

email = "budi@gmail.com"

linkedin = "linkedin.com/in/budisantoso"

portfolio = "github.com/budisantoso"

location = "Jakarta, Indonesia"

professional_summary = """
Fresh graduate dengan spesialisasi
Machine Learning dan Data Science
yang memiliki pengalaman membangun AI recommendation system menggunakan TensorFlow, Python, dan SQL.
"""

education = [

    {
        "university": "Universitas Indonesia",

        "location": "Jakarta, Indonesia",

        "degree": "Bachelor of Computer Science",

        "gpa": "3.85/4.00",

        "year": "2020 - 2024",

        "details": [

            "Asisten Laboratorium AI",

            "Ketua Komunitas Data Science",

            "Finalis AI Competition Nasional"
        ]
    }
]

experiences = [

    {
        "company": "PT AI Indonesia",

        "location": "Jakarta, Indonesia",

        "position": "Machine Learning Engineer Intern",

        "period": "Jan 2024 - Present",

        "responsibilities": [

            "Mengembangkan AI recommendation system menggunakan TensorFlow",

            "Membangun data pipeline menggunakan Python dan SQL",

            "Meningkatkan akurasi model sebesar 18%"
        ]
    }
]

projects = [

    {
        "title": "AI Career Recommendation System",

        "description": "Deep Learning recommendation system menggunakan TensorFlow",

        "details": [

            "Implementasi custom attention layer",

            "Membangun ATS CV Generator otomatis",

            "Menggunakan TensorFlow dan Python"
        ]
    }
]

certifications = [

    "TensorFlow Developer Certificate",

    "Google Data Analytics Professional Certificate"
]

achievements = [

    "Juara 1 National AI Competition 2024",

    "Top 10 Data Science Hackathon Indonesia"
]

skills = """
Python, SQL, TensorFlow,
Machine Learning,
Deep Learning,
Data Science,
Docker,
FastAPI,
Tableau
"""

languages = """
Indonesian (Native)

English (Professional Working Proficiency)
"""

generate_ats_cv(

    name=name,

    phone=phone,

    email=email,

    linkedin=linkedin,

    portfolio=portfolio,

    location=location,

    professional_summary=professional_summary,

    education=education,

    experiences=experiences,

    projects=projects,

    certifications=certifications,

    achievements=achievements,

    skills=skills,

    languages=languages,

    career_group=career_group,

    recommended_careers=recommended_careers,

    output_file="ATS_Professional_CV.docx"
)

files.download(
    "ATS_Professional_CV.docx"
)