# -*- coding: utf-8 -*-
"""ModelRecommendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dBVFdFblnAmhPR5OmulQ5ryPtgiSJ1C
"""

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.callbacks import (
    EarlyStopping,
    TensorBoard,
    Callback
)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

DATA_PATH = "dataset_clean.csv"

df = pd.read_csv(DATA_PATH)

print(df.shape)

df.head()

columns_used = [
    'keahlian',
    'minat',
    'pendidikan',
    'jurusan',
    'sertifikasi',
    'ipk',
    'label_karir_sederhana'
]

df = df[columns_used].copy()

def clean_text(text):

    text = str(text).lower()

    text = re.sub(
        r'[^a-zA-Z0-9 ]',
        ' ',
        text
    )

    text = re.sub(
        r'\s+',
        ' ',
        text
    )

    return text.strip()

text_columns = [
    'keahlian',
    'minat',
    'pendidikan',
    'jurusan',
    'sertifikasi'
]

for col in text_columns:

    df[col] = (
        df[col]
        .fillna("unknown")
        .apply(clean_text)
    )

df['ipk'] = (
    df['ipk']
    .fillna(0)
    .astype(str)
)

df['combined_text'] = (

    df['keahlian'] + ' ' +

    df['minat'] + ' ' +

    df['pendidikan'] + ' ' +

    df['jurusan'] + ' ' +

    df['sertifikasi'] + ' ' +

    df['ipk']
)

label_encoder = LabelEncoder()

df['label_encoded'] = (
    label_encoder.fit_transform(
        df['label_karir_sederhana']
    )
)

num_classes = len(
    label_encoder.classes_
)

print(num_classes)

with open(
    "label_encoder.pkl",
    "wb"
) as f:

    pickle.dump(
        label_encoder,
        f
    )

X_train, X_test, y_train, y_test = train_test_split(

    df['combined_text'],

    df['label_encoded'],

    test_size=0.2,

    stratify=df['label_encoded'],

    random_state=42
)

MAX_TOKENS = 10000
MAX_LEN = 100

text_vectorizer = layers.TextVectorization(

    max_tokens=MAX_TOKENS,

    output_mode='int',

    output_sequence_length=MAX_LEN
)

text_vectorizer.adapt(
    X_train
)

BATCH_SIZE = 64

train_ds = (
    tf.data.Dataset
    .from_tensor_slices(
        (X_train, y_train)
    )
    .shuffle(5000)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

test_ds = (
    tf.data.Dataset
    .from_tensor_slices(
        (X_test, y_test)
    )
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

@tf.keras.utils.register_keras_serializable()
class AttentionLayer(
    tf.keras.layers.Layer
):

    def __init__(self):

        super().__init__()

    def build(
        self,
        input_shape
    ):

        self.W = self.add_weight(

            shape=(
                input_shape[-1],
                1
            ),

            initializer="random_normal",

            trainable=True
        )

    def call(
        self,
        inputs
    ):

        score = tf.matmul(
            inputs,
            self.W
        )

        weights = tf.nn.softmax(
            score,
            axis=1
        )

        context = (
            weights *
            inputs
        )

        context = tf.reduce_sum(
            context,
            axis=1
        )

        return context

class AccuracyLogger(
    Callback
):

    def on_epoch_end(
        self,
        epoch,
        logs=None
    ):

        print(
            f"Epoch {epoch+1}"
            f" Accuracy={logs['accuracy']:.4f}"
        )

EMBEDDING_DIM = 64

@tf.keras.utils.register_keras_serializable()
class CareerModel(
    tf.keras.Model
):

    def __init__(self):

        super().__init__()

        self.vectorizer = text_vectorizer

        self.embedding = layers.Embedding(

            MAX_TOKENS,

            EMBEDDING_DIM,

            mask_zero=True
        )

        self.bigru = layers.Bidirectional(

            layers.GRU(

                64,

                return_sequences=True,

                dropout=0.3
            )
        )

        self.attention = AttentionLayer()

        self.dense = layers.Dense(

            128,

            activation='relu'
        )

        self.dropout = layers.Dropout(
            0.5
        )

        self.output_layer = layers.Dense(

            num_classes,

            activation='softmax'
        )

    def call(
        self,
        inputs
    ):

        x = self.vectorizer(inputs)

        x = self.embedding(x)

        x = self.bigru(x)

        x = self.attention(x)

        x = self.dense(x)

        x = self.dropout(x)

        return self.output_layer(x)

model = CareerModel()

model.compile(

    optimizer=tf.keras.optimizers.Adam(
        1e-3
    ),

    loss='sparse_categorical_crossentropy',

    metrics=['accuracy']
)

tensorboard = TensorBoard(
    log_dir="logs"
)

early_stop = EarlyStopping(

    monitor='val_loss',

    patience=3,

    restore_best_weights=True
)

history = model.fit(

    train_ds,

    validation_data=test_ds,

    epochs=20,

    callbacks=[

        early_stop,

        tensorboard,

        AccuracyLogger()
    ]
)

pred_probs = model.predict(X_test)

pred_labels = np.argmax(
    pred_probs,
    axis=1
)

print(
    classification_report(
        y_test,
        pred_labels
    )
)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        pred_labels
    )
)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir logs

cm = confusion_matrix(
    y_test,
    pred_labels
)

plt.figure(
    figsize=(10,8)
)

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.show()

model.save(
    "career_model.keras"
)

files.download(
    "career_model.keras"
)

files.download(
    "label_encoder.pkl"
)

model.summary()

def predict_career(
    skills,
    interests,
    education,
    major,
    certifications,
    gpa
):

    text = (
        f"{skills} "
        f"{interests} "
        f"{education} "
        f"{major} "
        f"{certifications} "
        f"{gpa}"
    )

    text = clean_text(text)

    prediction = model(
        tf.constant([text]),
        training=False
    )

    prediction = prediction.numpy()

    class_idx = np.argmax(prediction)

    confidence = float(
        np.max(prediction)
    )

    career = label_encoder.inverse_transform(
        [class_idx]
    )[0]

    return career, confidence

career_group, confidence = predict_career(

    skills="""
    Python SQL TensorFlow
    Deep Learning
    """,

    interests="""
    Artificial Intelligence
    Data Science
    """,

    education="S1",

    major="Informatika",

    certifications="""
    TensorFlow Developer
    """,

    gpa=3.8
)

CAREER_MAPPING = {

    "AI": [

        "Machine Learning Engineer",

        "AI Engineer",

        "Data Scientist",

        "Computer Vision Engineer",

        "NLP Engineer"
    ],

    "Data": [

        "Data Analyst",

        "Data Engineer",

        "Business Intelligence Analyst"
    ],

    "Software": [

        "Backend Developer",

        "Frontend Developer",

        "Full Stack Developer"
    ]
}

recommended_careers = CAREER_MAPPING.get(
    career_group,
    [career_group]
)

print(
    f"Predicted Category: {career_group}"
)

print(
    f"Confidence: {confidence:.2%}"
)

for career in recommended_careers:
    print(career)

print("career_group =", career_group)

print(
    "available mapping keys =",
    list(CAREER_MAPPING.keys())
)